use std::path::Path;

/// Returns the HTTP Content-Type for a file.
pub fn get_content_type(path: &Path) -> &'static str {
    match get_path_ext(path).as_str() {
        "ai" => "application/postscript",
        "apk" => "application/vnd.android.package-archive",
        "apng" => "image/apng",
        "avif" => "image/avif",
        "bin" => "application/octet-stream",
        "bmp" => "image/bmp",
        "com" => "application/octet-stream",
        "css" => "text/css; charset=utf-8",
        "csv" => "text/csv; charset=utf-8",
        "doc" => "application/msword",
        "docx" => "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "ehtml" => "text/html; charset=utf-8",
        "eml" => "message/rfc822",
        "eps" => "application/postscript",
        "exe" => "application/octet-stream",
        "flac" => "audio/flac",
        "gif" => "image/gif",
        "gz" => "application/gzip",
        "htm" => "text/html; charset=utf-8",
        "html" => "text/html; charset=utf-8",
        "ico" => "image/vnd.microsoft.icon",
        "ics" => "text/calendar; charset=utf-8",
        "jfif" => "image/jpeg",
        "jpeg" => "image/jpeg",
        "jpg" => "image/jpeg",
        "js" => "text/javascript; charset=utf-8",
        "json" => "application/json",
        "m4a" => "audio/mp4",
        "md" => "text/markdown; charset=utf-8",
        "mjs" => "text/javascript; charset=utf-8",
        "mp3" => "audio/mpeg",
        "mp4" => "video/mp4",
        "oga" => "audio/ogg",
        "ogg" => "audio/ogg",
        "ogv" => "video/ogg",
        "opus" => "audio/ogg",
        "pdf" => "application/pdf",
        "pjp" => "image/jpeg",
        "pjpeg" => "image/jpeg",
        "png" => "image/png",
        "ppt" => "application/vnd.ms-powerpoint",
        "pptx" => "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "ps" => "application/postscript",
        "rdf" => "application/rdf+xml",
        "rtf" => "application/rtf",
        "sh" => "application/x-sh; charset=utf-8",
        "shtml" => "text/html; charset=utf-8",
        "svg" => "image/svg+xml; charset=utf-8",
        "tex" => "application/x-tex; charset=utf-8",
        "text" => "text/plain; charset=utf-8",
        "tif" => "image/tiff",
        "tiff" => "image/tiff",
        "toml" => "application/toml; charset=utf-8",
        "ts" => "text/typescript; charset=utf-8",
        "tsx" => "text/typescript; charset=utf-8",
        "txt" => "text/plain; charset=utf-8",
        "vtt" => "text/vtt; charset=utf-8",
        "wasm" => "application/wasm",
        "wav" => "audio/wav",
        "weba" => "audio/webm",
        "webm" => "video/webm",
        "webp" => "image/webp",
        "xbl" => "text/xml; charset=utf-8",
        "xbm" => "image/x-xbitmap",
        "xht" => "application/xhtml+xml",
        "xhtml" => "application/xhtml+xml",
        "xls" => "application/vnd.ms-excel",
        "xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xml" => "text/xml; charset=utf-8",
        "xsl" => "text/xml; charset=utf-8",
        "yaml" | "yml" => "application/yaml; charset=utf-8",
        "zip" => "application/zip",
        _ => "application/octet-stream",
    }
}

pub fn get_path_ext(path: &Path) -> String {
    path.extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| ext.to_ascii_lowercase())
        .unwrap_or_default()
}
