[package]
name = "edotex"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tectonic = "0.17.0"
include_dir = "0.7"
tectonic_bridge_core = "0.5.3"
axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
chrono = "0.4"
httpdate = "1.0.3"
